AE-1561: common averages can be null
solita/etp-core pull request #715
Opened 2021-10-13 10:45 UTC by solita-tonipu

2021-10-13 11:22 UTC, muep requested changes, later dismissed

2021-10-13 11:22 UTC, muep commented on etp-backend/src/main/clj/solita/etp/schema/statistics.clj
> +                           :lto-vuosihyotysuhde            common-schema/NonNegative
Näihin `:lto-vuosihyotysuhde` ja `:ivjarjestelma-sfp` taidetaan tarvita nämä myös

2021-10-13 14:10 UTC, hkorpi commented on etp-backend/src/main/clj/solita/etp/schema/statistics.clj
> +                           :ivjarjestelma-sfp              (schema/maybe common-schema/NonNegative)})
mites nämä muut?
pakollisia tietoja näissä on vain ilmanvuotoluku ja ulkoseinien u-arvo.

2021-10-13 14:12 UTC, hkorpi commented on etp-backend/src/main/clj/solita/etp/schema/statistics.clj
> +                           :ivjarjestelma-sfp              (schema/maybe common-schema/NonNegative)})
eli jos haku kohdistuu et joukkoon jossa nämä on tyhjiä niin eikö silloin avg:stä tule null?

2021-10-14 05:30 UTC, muep commented on etp-backend/src/main/clj/solita/etp/schema/statistics.clj
> +                           :ivjarjestelma-sfp              (schema/maybe common-schema/NonNegative)})
Näin siinä taitaa käydä. Nuo [nullifit](https://github.com/solita/etp-core/blob/develop/etp-backend/src/main/sql/solita/etp/db/statistics.sql#L62) kyllä lisäävät todennäköisyyttä saada `null`, mutta voihan sen saada varmaan kaikista viimeistään sitten jos sattuu olemaan tyhjä joukko.

2021-10-14 09:20 UTC, hkorpi approved these changes
MapEntry:n sijaan toimisi varmaan [] ja toimiikohan oikeasti syvään rakenteeseen? Tuleeko kaikesta maybe vai vain lehdistä? mutta joo toimii ainakin noihin kahteen käyttötapaukseen kun on vain flatti objekti

2021-10-14 09:30 UTC, merged