Add option to search valvonta by asiakirjapohja
solita/etp-core pull request #921
Opened 2023-06-29 09:56 UTC by solita-antti-mottonen

2023-06-29 11:30 UTC, muep approved these changes

2023-06-30 06:58 UTC, Juholei requested changes

2023-06-30 06:58 UTC, Juholei commented on etp-backend/src/test/clj/solita/etp/valvonta_test.clj
> +    [clojure.set]
Miksi nämä on requireina? Corea ei tarvitsisi ikinä requireta erikseen ja tällaisenaan nämä eivät tee mitään, kun ei ole määritelty aliasta tai sieltä referoitavia funktioita. Tämän tyyliset requiret ovat tarpeen ainoastaan, jos pelkkä namespacen require aiheuttaa jo sivuvaikutuksia.

2023-06-30 06:58 UTC, Juholei commented on etp-backend/src/test/clj/solita/etp/valvonta_test.clj
> +  (if (some? (k m)) (assoc m k (.toString (k m))) m))
Tässä voisi olla varmaankin .toStringin sijaan vain str-kutsu. Rivittäisin myös luettavuuden vuoksi ifin ehdon ja haarat omille riveilleen

2023-06-30 06:58 UTC, Juholei commented on etp-backend/src/test/clj/solita/etp/valvonta_test.clj
> +      (with-redefs [solita.etp.service.suomifi-viestit/send-message! assert-suomifi-message-sent]
Tähän mieluummin tuo namespacen alias takaisin kuin koko fully qualified namespacen nimi

2023-06-30 06:58 UTC, Juholei commented on etp-backend/src/test/clj/solita/etp/valvonta_test.clj
> +                                     ((fn [valvonta] (assoc valvonta :id (valvonta-service/add-valvonta! ts/*db* valvonta))))))
Mieluusti tämä funktion määritys tuohon ylempään letiin, niin on mielestäni luettavampi kuin että luodaan anonyymi funktio ja kutsutaan sitä heti samassa yhteydessä

2023-06-30 06:58 UTC, Juholei commented on etp-backend/src/test/clj/solita/etp/valvonta_test.clj
> +                      (map vector (flatten (repeatedly (constantly '(1 2)))))
'()-syntaksilla määriteltäviä listoja on harvemmin tapana käyttää koodissa, mieluummin käyttää vektoreita kun niitä yleensä voi käyttää ihan huoletta toisiaan vastaavina asioina. Eli [1 2] siinä tapauksessa tähän.

2023-06-30 06:58 UTC, Juholei commented on etp-backend/src/test/clj/solita/etp/valvonta_test.clj
> +        _ (doall (->> (repeatedly 12 (fn [] (generators/complete {} valvonta-schema/ToimenpideAdd)))
Pääsisikö doallista eroon jos tässä käyttäisi mapin sijaan mapv:tä?

2023-06-30 06:58 UTC, Juholei commented on etp-backend/src/test/clj/solita/etp/valvonta_test.clj
> +                      (map (fn [[valvonta-id toimenpide]]
Lopullisesta paluuarvosta ei olla ilmeisesti kiinnostuneita, joten tarvitaanko tämän mapin sisällä tuota merge-kutsua? Myöskin koska tässä tehdään sivuvaikutuksia, ottaisin ehkä tuolla ylempänä letissä kiinni paluuarvon tuohon edelliseen steppiin asti ja korvaisin tämän sitten letin sisällä tehtävällä doseqillä, koska se on tarkoitettu sivuvaikutusten tekemiseen.

2023-06-30 06:58 UTC, Juholei commented on etp-backend/src/test/clj/solita/etp/valvonta_test.clj
> +    (t/testing "Valvonnalle palautetataan 6 toimenpidettä"
Kirjoitusvirhe

2023-06-30 06:58 UTC, Juholei commented on etp-backend/src/test/clj/solita/etp/valvonta_test.clj
> +(defn- non-null-key-to-string [m k]
Tälle olisi ehkä idiomaattisempi nimi non-nil-key->string

2023-06-30 06:58 UTC, Juholei commented on etp-backend/src/test/clj/solita/etp/valvonta_test.clj
> +        toimenpiteet (doall (->> (repeatedly 2 (fn [] (generators/complete {} valvonta-schema/ToimenpideAdd)))
Samat mietteet doallin, mapin, vektorin ja doseqin käytöstä tähänkin kuin ylempänä.

2023-06-30 11:57 UTC, Juholei commented on etp-backend/src/test/clj/solita/etp/valvonta_test.clj
> +(defn- add-valvonta-and-map-id [valvonta]
Näihin kahteen funktioon vielä ! nimen perään, koska tallentavat kantaan dataa ja sen myötä aiheuttavat sivuvaikutuksia

2023-06-30 12:33 UTC, Juholei approved these changes

2023-06-30 12:34 UTC, merged