Update WSS4J
solita/etp-core pull request #929
Opened 2023-07-07 06:17 UTC by solita-antti-mottonen

WSS4J is the library used for signing soap messages sent to Suomi.fi. The previous implementation was apparently made using the official example, that to this day still uses the obsolete version of WSS4J.

The details of what should happen in signing are scarce. Created a test that compares a document signed with the previous version of the library to a new one. Cryptographic elements cannot be compared easily, so the test instead just checks that all the correct elements are in place.

2023-07-07 09:43 UTC, Juholei requested changes

2023-07-07 09:43 UTC, Juholei commented on etp-backend/src/main/clj/solita/etp/service/suomifi_viestit.clj
> +        os (ByteArrayOutputStream.)]
Voisiko tässä olla with-open ympärillä, joka varmistaa että output-stream suljetaan blokista poistuttaessa?

2023-07-07 09:43 UTC, Juholei commented on etp-backend/src/main/clj/solita/etp/service/suomifi_viestit.clj
> +    (doto (WSSecTimestamp. header)
Minne tämä menee?

2023-07-07 09:43 UTC, Juholei commented on etp-backend/src/test/clj/solita/etp/service/suomifi_viestit_test.clj
> +                              (t/is false comparison))))
Tästä puuttunee = tarkistus?

2023-07-07 09:43 UTC, Juholei commented on etp-backend/src/test/clj/solita/etp/service/suomifi_viestit_test.clj
> +  (with-bindings {#'solita.etp.service.suomifi-viestit/post! (handle-request-with-xml-compare "suomifi/viesti-request-signed.xml"
Tähän namespacen alias kanssa kuten ylempänä on

2023-07-07 09:50 UTC, solita-antti-mottonen commented on etp-backend/src/main/clj/solita/etp/service/suomifi_viestit.clj
> +    (doto (WSSecTimestamp. header)
Se ilmeisestikin injektoi itsensä headeriin `build`issa. Ainakaan koodi ei toimi ilman sitä.

2023-07-07 09:51 UTC, solita-antti-mottonen commented on etp-backend/src/test/clj/solita/etp/service/suomifi_viestit_test.clj
> +                              (t/is false comparison))))
ComparisonListeneriä kutsutaan pieleen menneillä vertailuilla, jolloin tässä feilataan testi. Lisään selittävän kommentin.

2023-07-07 10:43 UTC, Juholei approved these changes

2023-07-13 11:24 UTC, merged

2023-07-13 12:02 UTC, Juholei commented
Testattu toimivaksi testiympäristössä.